---
- hosts: test
  become: yes
  tasks:

  - name: Installing apache pkg
    apt:
        name: apache2
        state: absent

  - name: install php
    apt: 
        name: libapache2-mod-php
        state: absent
...
